backend:
  name: github-proxy
  repo: danieligazit/orthodox-records
  branch: main
  base_url: https://decap-oauth-proxy.danieligazit.workers.dev

media_folder: "public"
public_folder: "/"


collections:
  - name: "data"
    label: "Data"
    files:
      - name: "albums"
        label: "Albums"
        file: "src/data/albums.json"
        description: "List of albums"
        fields:
          - label: "Albums"
            name: "albums"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "URL Path (Slug)", name: "urlPath", widget: "string", hint: "e.g. 'turn-of-a-millstone'"}
              - {label: "Artist", name: "artist", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Release Date", name: "releaseDate", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
              
              - label: "Cover Image"
                name: "cover"
                widget: "image"
                choose_url: false
                media_library:
                  config:
                    multiple: false

              - {label: "Bandcamp Embed ID", name: "bandcampEmbedId", widget: "number", value_type: "int", required: false}

              - label: "Description"
                name: "description"
                widget: "object"
                fields:
                  - label: "Paragraphs"
                    name: "paragraphs"
                    widget: "list"
                    summary: '{{fields.paragraph}}'
                    field: {label: "Paragraph", name: "paragraph", widget: "text"}
                  
                  - label: "Credits"
                    name: "credits"
                    widget: "object"
                    fields:
                      - {label: "Artists", name: "artists", widget: "list", required: false, field: {label: "Line", name: "line", widget: "string"}}
                      - {label: "Additional", name: "additional", widget: "list", required: false, field: {label: "Line", name: "line", widget: "string"}}
                      - {label: "Production", name: "production", widget: "list", required: false, field: {label: "Line", name: "line", widget: "string"}}
                      - {label: "Cover Art Credits", name: "coverArt", widget: "list", required: false, field: {label: "Line", name: "line", widget: "string"}}